stages:
  - build

build:
  stage: build
  image: docker:stable
  tags: 
    - deploy
    - docker
    
  before_script:
    - docker info

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull gitlab.unosalon.ml:4567/containers/flask:latest
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
